name: vamos
channels:
  - robostack-noetic
  - conda-forge
  - pytorch
  - nvidia
  - defaults

variables:
  # Let legacy CMakeLists (cmake_minimum_required(VERSION 3.0.2)) configure
  CMAKE_POLICY_VERSION_MINIMUM: "3.5"

dependencies:
  # ROS Noetic core (this pulls Python, rospy, etc.)
  - ros-noetic-desktop

  # Image transport plugins used by your launch file
  - ros-noetic-image-transport-plugins
  - ros-noetic-compressed-image-transport
  # (compressedDepth is still provided by compressed_depth_image_transport inside robostack in some builds,
  #  but if it's not published for linux-64 we can't list it here explicitly. We'll rely on whatever comes with plugins.)

  # Build / workspace tooling
  - catkin_tools
  - colcon-common-extensions
  - cmake=3.22
  - make
  - ninja
  - pkg-config

  # Core ML / GPU
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - cudatoolkit=11.8

  # Vision / SciPy stack
  # IMPORTANT: pin OpenCV to 4.10 so libopencv_core.so.410 exists
  - opencv=4.10
  - pillow
  - matplotlib
  - scipy
  - scikit-learn
  - pandas

  # Web / API
  - fastapi
  - uvicorn
  - pydantic

  # Utilities
  - psutil
  - tqdm

  # Jupyter / dev
  - jupyter
  - ipykernel
  - notebook

  # ONNX / interop
  - onnx
  - onnxruntime

  # pip ecosystem
  - pip
  - pip:
      - transformers
      - peft
      - accelerate
      - huggingface-hub
      - datasets
      - tokenizers
      - "optimum[exporters]"
      - "optimum[onnxruntime]"
