name: vamos
channels:
  - robostack-noetic
  - conda-forge
  - pytorch
  - defaults
  - nodefaults

variables:
  CMAKE_POLICY_VERSION_MINIMUM: "3.5"

dependencies:
  - python=3.11

  # ROS core stack
  - ros-noetic-desktop

  # build / workspace tooling
  - catkin_tools
  - colcon-common-extensions
  - cmake
  - make
  - ninja
  - pkg-config

  # vision / science stack
  - opencv=4.10
  - pillow
  - matplotlib
  - scipy
  - scikit-learn
  - pandas

  # web / infra / utils
  - fastapi
  - uvicorn
  - pydantic
  - psutil
  - tqdm

  # notebooks / dev
  - jupyter
  - ipykernel
  - notebook

  # ONNX / interop
  - onnx
  - onnxruntime

  # lightweight CPU torch placeholder just to satisfy solver;
  # we'll override it via pip with GPU torch.
  - pytorch
  - torchvision

  - pip
  - pip:
      # 1. Point pip to the CUDA 12.1 wheel index for the next installs
      - --index-url https://download.pytorch.org/whl/cu121

      # 2. Install GPU-enabled PyTorch stack (CUDA 12.1 builds)
      #    These versions exist on the cu121 index.
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1

      # 3. Your ML / HF stack
      - transformers
      - peft
      - accelerate
      - huggingface-hub
      - datasets
      - tokenizers
      - "optimum[exporters]"
      - "optimum[onnxruntime]"
